### ISSUE TITLE
TargetPort?

### ISSUE THREAD

**Issue by grvs1404** [angeldeejay/MMM-WyzeBridge#2]
What port is the standard port for this module to see the Cameras? I have tried 5000 several others and I'm not seeing anything. In the error logs it says, No Cameras found, failed with status code 404.

**Comment by angeldeejay** [comment]
This module is a port of [Wyze-Bridge](https://github.com/mrlt8/docker-wyze-bridge). The logs you saw are from that software. 

That software is meant to work only with cameras attached to a valid Wyze account directly. `No cameras found` message commonly means that:
- You have no cameras attached to a valid Wyze Account
- Your Wyze Account credentials are incorrect

Please refer to [Wyze-Bridge](https://github.com/mrlt8/docker-wyze-bridge) docs to fix your Wize-Bridge server instance issue.
